apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: default-scheduler
      resourceNamespace: kube-system
    profiles:
    - schedulerName: default-scheduler
      plugins:
        filter:
          enabled:
          - name: PodCountByNode
        score:
          enabled:
           - name: LoadVariationRiskBalancing
      pluginConfig:
      - name: PodCountByNode
        args:
          podCountLimit:
            - nodeLabels:
                node-role.kubernetes.io/master: ""
              podNamespace: dev
              count: 3